### ISSUE TITLE
Proposal: Change all "console." to "debug("

### ISSUE THREAD

**Issue by FernandoMorais** [strongloop/loopback-datasource-juggler#1004]
Hi all!

I've made a pr in debug project that permits the using of custom loggers (winston) loaded in domain, so now the next step is evolve other modules in our project (based on loopback) to just output messages using debug module (or other logging libraries).

I think this is a good way to do that, so if you considere these changes aligned with the project's roadmap I could do a pr right now.

Regards!

**Comment by Amir-61** [comment]
A simple search through the repository shows the `console.log`s are not used in `/lib` folder; they are mostly used under `/docs`, `/test` and `/examples` folders; I'm closing this issue now since it does not receive enough interest from the community either... however please feel free to send PRs to fix them...

Thanks!
