### ISSUE TITLE
operation hook `loaded` has wrong context for `find()` in 2.x

### ISSUE THREAD

**Issue by benkroeger** [strongloop/loopback-datasource-juggler#1071]
the context object provided to `loaded` operation hook includes an `instance` property but no `data` property.
https://github.com/strongloop/loopback-datasource-juggler/blob/2.x-latest/lib/dao.js#L1723

All other `loaded` hooks provide `data` with the `context` object so that one could manipulate the raw data before a model instance is created.

the current master (3.x alpha) has this fixed already

**Comment by Amir-61** [comment]
@jannyHou 
The Pull request links you provided are not the ones which change `loaded` hook for `DAO.find`; [PR#796](https://github.com/strongloop/loopback-datasource-juggler/pull/796) is the one which changes `loaded` hook for `DAO.find` to use `data` and not `instance`; I'm pretty sure @bajtos did not back port it to `loopback-datasource-juggler@2.x` on purpose because it was a breaking change; he can confirm it.

**Comment by jannyHou** [comment]
@Amir-61 ok thank you lol, git blame directs me to a wrong pr.
Looks like we replaced `instance` with `data` in 3.x. @bajtos could you help confirm it? Thanks!

**Comment by bajtos** [comment]
Yes, I have intentionally not back-ported the fix, as I consider it a breaking change.
