### ISSUE TITLE
add getAsync to documentation and clarify others

### ISSUE THREAD

**Issue by ludicruz** [strongloop/loopback-datasource-juggler#1127]
I only found the Promise getAsync function from reading the juggler tests, could this be added to the documentation?

also the documentation says customer orders takes a where clause but it should be a filter correct?

in the documentation

```
customer.orders([where], function(err, orders) {
  ...
});
```

should this be:

```
customer.orders([filter], function(err, orders) {
  ...
});
```

and for the Promise interface

```
customer.orders.getAsync([filter]).then(function(orders) {
  ...
});
```

???

found on this test:
https://github.com/strongloop/loopback-datasource-juggler/blob/2cb0d042e4936270540ee8fdfa04939430936b9c/test/relations.test.js#L197

the new documentation does not show anything about getAsync:
http://loopback.io/doc/en/lb2/HasMany-relations.html

nor does the old:
https://docs.strongloop.com/display/public/LB/HasMany+relations

**Comment by Amir-61** [comment]
>also the documentation says customer orders takes a where clause but it should be a filter correct?

That's right; this is a documentation issue; Please see code [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/scope.js#L177-L205) which shows we support`filter`.


>the new documentation does not show anything about getAsync
>nor does the old

Yes you are right; it needs to be added in documentation.

@crandmck

**Comment by crandmck** [comment]
I updated http://loopback.io/doc/en/lb2/HasMany-relations.html#methods-added-to-the-model to change it to `filter`.

Re `getAsync`: 
- Is this just for HasMany relations, or also for others?
- Is it only when using Promises?  In general, we haven't really documented the Promises API because it's incompletely implemented....

**Comment by ludicruz** [comment]
> Is this just for HasMany relations, or also for others?

I have been using the getAsync consistently for a while now.
I looked through where I've been using it and it's being used with `BelongsTo` and `HasMany`
FWIW: the `HasMany` relationships I've been using are normal (whatever that means...), through, and polymorphic.

> Is it only when using Promises? In general, we haven't really documented the Promises API because it's incompletely implemented....

This is in a few others as well.

Hope this helps.. I would have been using this sooner if I saw it in the documentation! 😃

**Comment by gunjpan** [comment]
@ludicruz : `getAsync()` was added in this commit: https://github.com/strongloop/loopback-datasource-juggler/commit/29eb3434c764903562e68f135826560649361700 

> getAsync(condition, cb)
A new method "getAsync()" has been added to all relations except
EmbedsMany, which always fetches from the datasource rather than from
the cache.  It takes an optional "where" condition (except for HasOne
and BelongsTo) and an optional callback.  If the callback is omitted,
a Promise is returned.

**Comment by lehni** [comment]
From looking through the code, the `getAsync()` is defined in 3 places: `BelongsTo`, `HasOne` and `HasMany`, which is implemented as a scope. Therefore, it is also present on all scopes.  

I find it's naming really strange though:

- It is the only function with `Async()` in its name
- Like all other functions on relationships (`create`, `update`, `count`, etc), it accepts a callback function and returns a promise if none is provided

I would like to suggest to rename it simply to `get`, while keeping the `getAsync` around for backward compatibility. I was also thinking about `find`, but I guess that wouldn't make sense on `BelongsTo`, `HasOne`?

@partap, @bajtos what do you think about this proposal? I am happy to create a PR for it...

**Comment by bajtos** [comment]
The name `getAsync` was chosen deliberately after a long discussion in  https://github.com/strongloop/loopback-datasource-juggler/pull/452, I think this is the first relevant comment: https://github.com/strongloop/loopback-datasource-juggler/pull/452#issuecomment-78421359.

> I would like to suggest to rename it simply to `get`

See https://github.com/strongloop/loopback-datasource-juggler/pull/452#issuecomment-82425368: _we already have get() on EmbedsMany relations_

Please read the full discussion to better understand why `getAsync` was chosen at the end.

I think the idea of finding a better name for `getAsync` is a good one, we just need to find a better name than `get` - a name that's not already used in dao/relations/embedded-relations for a possibly different task.

> while keeping the `getAsync` around for backward compatibility

Yes please. We can even mark `getAsync` as deprecated, we are/have been using [depd](https://www.npmjs.com/package/depd) for that.

**Comment by lehni** [comment]
@bajtos thanks for getting back about this, and pointing me to the previous discussion! I wasn't aware of it. From what I've read now, it sounds like `find()` wouldn't be a bad name for it, still? After all, `Model.find()` also returns an array, not a single instance?

**Comment by bajtos** [comment]
@lehni you are welcome!

`getAsync` returns a single instance for `belongsTo` relation. If we added `find` as an alias for `getAsync`, then I would find it confusing that `find` returns a single instance, considering that other find methods return an array of instances.

For example, consider a `Customer` model with `hasMany` relationship to an `Order` model, `customer` holding an instance of `Customer, `order` holding an instance of `Order`.

 - `customer.orders.find()` returns a promise of an array
 - `order.customer.find()` returns a promise of a single instance

Another difference to consider: For `customer.orders.find()`, it makes sense to allow a `filter` argument to limit the orders searched. Not so for `order.customer.find()`, because it's returning only a single instance.

How do you feel about these inconsistencies?

**Comment by lehni** [comment]
@bajtos yes, that does make sense. I realized my mistake in the meantime as well...

But do they all need the same name necessarily? In the source-code, `getAsync()` is defined in three places, separately for `BelongsTo`, `HasOne` and `HasMany` (through scopes). It could easily be `find()` for scopes / `HasMany` (mirroring `Model.find()`, which does make sense), and something else for `BelongsTo` and `BelongsTo`?

Since `fetch()` is taken an `get()` is problematic, how about `retrieve()`?

**Comment by bajtos** [comment]
>  It could easily be `find()` for scopes / `HasMany` (mirroring `Model.find()`, which does make sense), and something else for `BelongsTo` and `BelongsTo`?

I agree it's a good idea to use different names.

> Since `fetch()` is taken an `get()` is problematic, how about `retrieve()`?

Sounds good.

**Comment by lehni** [comment]
Great, shall I create a PR for it?

**Comment by bajtos** [comment]
> Great, shall I create a PR for it?

@lehni Yes please! Just mention my GH handle in the pull request description, so that I receive an email notification and can review the changes (I am not following all new juggler pull requests.)

**Comment by lehni** [comment]
Looking into this a bit more this morning, I found other discrepancies...

`get()` on `EmbedsMany` is a reference to `findById()`, which takes a callback or returns a value synchronously in the absence of the callback (hence the issue with naming things `get()` in other places). But there are plenty of other cases where `findById()` returns asynchronously (all of the others?), so the same problem that was pointed out when naming `getAsync()` `get()` applies here already, and wasn't seen as a problem...

Generally it feels like the loopback-datasource-juggler API is quite messy, and has many such naming discrepancies. e.g. why is the method to delete an instance called `deleteById()` on the Model, but `prototype.__destroyById__...()` for relationships on the instance? I know there are aliases, but when working  with `Model.disableRemoteMethodByName()`, this is the naming that I need to adhere to for it to work (and the aliases just further confuse things there). I hope these things are getting addressed in loopback-next!

**Comment by lehni** [comment]
Here all the examples of methods I could find where `EmbedsMany` returns synchronously, while the others (`HasMany`, `HasManyThrough`, `ReferencesMany`, `DataAccessObject`, ...) return promises (if they define them at all):

`at()`
`exists()`
`updateById()`
`updateById()`
`destroyById()`

These can easily be found by searching for `// sync` in the source code. I don't think this has caused concern or confusion so far?

Based on this observation, I really think that naming these methods simply `get()` is the best we can do), and the most aligned with how things are currently are named and implemented, including this discrepancy that's hard to fix at this point. Except for scopes of course, where I think we should name it `find()`, as pointed out above.

@bajtos does this sound reasonable?

**Comment by bajtos** [comment]
@lehni thank you for the research and a detailed analysis. To be honest, juggler and it's API is not my area of expertise. Your proposal look reasonable to me. Would you mind opening a pull request with the proposed new methods/aliases, so that we can figure out the naming nuances there?

**Comment by HarisHashim** [comment]
Still no documentation.

1. I first google and get Using Promises docs https://loopback.io/doc/en/lb2/Using-promises.html

2. Follow the doc code example and try to apply it to my relation belong to method

```
MyModel.find()
   .then(function(result){
``

3. Does not work! Ask question in gitter. 

4. Google and found similar problem in this [issue](https://github.com/strongloop/loopback/issues/2595).

5. Google again and found issue [452](https://github.com/strongloop/loopback-datasource-juggler/pull/452) . Which conclude by saying documentation is needed.

6. Finally bring me to this issue!

All this should stop at step 1. Some example how to use getAsync() or get() in doc at step one will helps LoopBack user alot!

**Comment by bajtos** [comment]
@HarisHashim thank you for the feedback.

> I first google and get "Using Promises" docs https://loopback.io/doc/en/lb2/Using-promises.html

FWIW, this is pointing to 2.x docs which may be outdated by now. It's usually better to refer to the latest 3.x docs, there is a notice with a link at the top of all 2.x doc pages. 

> All this should stop at step 1. Some example how to use getAsync() or get() in doc at step one will helps LoopBack user alot!

I totally agree! Could you make it happen yourself? See http://loopback.io/doc/en/contrib/doc-contrib.html to get you started.

**Comment by HarisHashim** [comment]
@bajtos about the doc 2.0 vs 3.0. I normally do that. I.e. when search on google, (for some reason) I will get  loopback 2.0 and I would just click a link to go to loopback 3.0.

The thing about user contributing documentation is that they first need to understand what to document. This is chicken and egg situation. Probably a comprehensive example of how promise work in LoopBack will help. Otherwise, I will have to spend about a week to dig information and come up with my own example. That is time that I don't have.

Maybe, I can help in the future. When I am better at understanding stuff. Probably when someone is working on something to be released and I can get involved at earlier stage. For instance when test is done. And I can ask question to the person who contribute code etc.

**Comment by charlie-s** [comment]
What's a good way to word this in the docs? How about this for starters, at the very bottom of https://loopback.io/doc/en/lb3/Using-promises.html:

### DAO and relation methods

`BelongsTo` and `HasOne` relations return promises by calling the `get()` method on the relation property:

```javascript
MyModel.relation.get()
  .then(function(result) {
    // ...
  });
```

`HasMany` relations return promises by calling the `find()` method on the relation property:

```javascript
MyModel.relations.find()
  .then(function(results) {
    // ...
  });
```

**Comment by bajtos** [comment]
Sorry for the long silence on our side.

> What's a good way to word this in the docs? 

Personally, I'd like to see these methods documented here:
 - https://loopback.io/doc/en/lb3/BelongsTo-relations.html#methods-added-to-the-model
 - https://loopback.io/doc/en/lb3/HasOne-relations.html#methods-added-to-the-model
 - https://loopback.io/doc/en/lb3/HasMany-relations.html#methods-added-to-the-model

I don't remember if other relations come with this new promise-only API. If they do, then the following pages should be updated too:
 - https://loopback.io/doc/en/lb3/HasManyThrough-relations.html#methods-added-to-the-model
 - https://loopback.io/doc/en/lb3/HasAndBelongsToMany-relations.html#methods-added-to-the-model
 
> How about this for starters, at the very bottom of https://loopback.io/doc/en/lb3/Using-promises.html.

I agree it makes sense to mention these new APIs on the page describing how to use Promises in LoopBack. Let's implement this proposal too.

@charlie-s could you please contribute these improvements yourself? Here is our contribution guide to get you started: https://loopback.io/doc/en/contrib/doc-contrib.html

Please mention my GitHub handle in your pull request so that I get a notification from GitHub and can take help you to get the changes landed quicker.
