### ISSUE TITLE
Refactor DAO.find()

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback-datasource-juggler#1152]
`DataAccessObject.find` is long spaghetti code we need to refactor this method and split it into smaller chunks.

**Comment by loay** [comment]
Few attempts of refactoring have been tried in order to extract the interior functions such as 
`withNotifyGeo` , `queryGeo` and `buildResult`..
Though `withNotifyGeo`  and  `queryGeo` were a success on the juggler level as shown here: https://github.com/strongloop/loopback-datasource-juggler/pull/1469
where both commits are 2 separate  attempts of refactoring.

Unfortunately, they were broken on the connectors level. The `find` function is mainly a static one `DAO.find`, so the scope of `self` was completely different when the functions are extracted outside `DAO.find` as `self` is not the same at all as the scope has completely changed, where it led to breaking the tests in most of the connectors either `SQL` and `NoSQL`. 
The connector does not recognize the `self` instance such as for example `self.getConnector`
