### ISSUE TITLE
Having forceId set to true by default breaks replace method

### ISSUE THREAD

**Issue by joostdebruijn** [strongloop/loopback-datasource-juggler#1171]
When I try to replace an existing model instance via the replaceOrCreate-method (both internal as remote), I receive an error like:  `ValidationError: The 'Model' instance is not valid. Details: 'id' can't be set (value: 9)`. In the model settings, forceId = true, when I disable it I can use the replaceOrCreate-method without an error. So it seems that the forceId-check is triggered because I submit an `id`. However, I don't think this behaviour is completely right, because it makes the replaceOrCreate-method useless when having forceId enabled.

My suggestion to fix this:

1. Check if the `id` exists;
2. If the `id` exists, replace the particular model instance;
3. If the `id` does not exists, throw an error.

**loopback-datasource-jugger:** v3.0.0
**loopback-connector-mysql** v2.4.0
**Node.js:** v7.2.0 (Windows 10, build 1607)

**Comment by Amir-61** [comment]
Hey @joostdebruijn,

>When I try to replace an existing model instance via the replaceOrCreate-method (both internal as remote), I receive an error like: ValidationError: The 'Model' instance is not valid. Details: 'id' can't be set (value: 9). In the model settings, forceId = true, when I disable it I can use the replaceOrCreate-method without an error.

Yes `forceId = true` contradicts with the goal of `replaceOrCreate`; I expect this error for replace operation of`replaceOrCreate` when `forceId = true`; let me explain, `replaceOrCreate` uses the PK; for `replace` operation of `replaceOrCreate` you always need to provide the PK; that means if you pass the PK and the PK exists in the backing datasource, it replaces that instance with the new data provided; however, if you use `forceId: true` it means we are preventing users from passing the PK; that's why if the `forceId` is set to `true` and you attempt to replace an instance with providing an existing PK, it will throw the error you mentioned.

Since `forceId = true` contradicts with the end goal of `replaceOrCreate` and it does not let you replace an instance with providing the PK of an existing instance, I believe setting `forceId` to true for auto-increment databases by https://github.com/strongloop/loopback-datasource-juggler/pull/982 is not the right either; let's discuss this here; @bajtos @jannyHou any thought?

**Comment by jannyHou** [comment]
Hmm, I agree that we should not set default `forceId` to `true` on connectors that not using Integer ID, like mongodb and cloudant.

**Comment by Amir-61** [comment]
>Hmm, I agree that we should not set default forceId to true on connectors that not using Integer ID, like mongodb and cloudant.

Well my point is the end goal of `replaceOrCreate` contradicts with having `forceId` as True, not only for the databases you mebtioned (Mongodb and Cloudant), but also other databases... IMO by default having it set to true is debatable for any connectors.

**Comment by jannyHou** [comment]
I am confused whether `updateOrCreate` also fails? If it can pass, then we should be possible to do `replaceOrCreate` with `forceId: true` as well.

And if update methods also fail, from my understanding, we need to refactor replace/update method to satisfy the goal:
```
Check if the id exists;
If the id exists, replace the particular model instance;
If the id does not exists, throw an error.

```
It doesn't make sense to me that `replace/update` and `create` have to share same validation rules.
Thoughts?

**Comment by Amir-61** [comment]
>I am confused whether updateOrCreate also fails? If it can pass, then we should be possible to do replaceOrCreate with forceId: true as well.

Yes if `forceId` is set, it breaks `updateOrCreate` as well... for `updateOrCreate` you need to pass the PK if you want to update a pre-existing instance and if `forceId` is set to true you will get similar to the following validation error:

```
ValidationError: The `customer` instance is not valid. Details: `id` can't be set (value: 5).
```

**Comment by jannyHou** [comment]
> No I don't think if the above ^ approach is the right way to do it
Then any idea on fixing https://github.com/strongloop/loopback-datasource-juggler/issues/849?

**Comment by jannyHou** [comment]
Forget forceId thing, I think the conflict here is:
- replaceOrCreate/updateOrCreate need to allow users provide PK
- security issue need to forbid users provide PK

And my opinion is replace/update an existing instance with any PK is reasonable, but create instance with any PK is pretty dangerous.

**Comment by Amir-61** [comment]
Yes I agree that `forceId` enforcement should be valid for create operation (NOT update/replace operation) of `replaceOrCreate`, `updateOrCreate` and possibly `findOrCreate`...

**Comment by bajtos** [comment]
Hi, I think this is a major usability bug, I am re-labelling it as such.

Here are my thoughts on how to approach this issue:

As I understand the idea behind `replaceOrCreate` and `replaceOrUpdate`, it allows the client to use a single HTTP endpoint for both creating a new instance and updating an existing one, so that it's easy to implement a generic `$save` method:

```js
// returns a promise
MyClientModel.prototype.$save = {
  return MyClientModel.replaceOrCreate(this);
}
```

Now with `forceId` set, we are expecting clients to never provide an `id` field for new instances. In other words, if the instance data contains an id, then the assumption is that this is an existing instance.

In that case, there are two valid situations we need to support:
 - `replaceOrCreate` is invoked with data with no `id` field set and the user wants to create a new instance
 - `replaceOrCreate` is invoked with data that contains an `id` field and the user wants to update an existing instance

The third situation, where `replaceOrCreate` is invoked with data that contains an `id` field but where there is no such `id` in the database, is not a valid usage in this configuration and such call should fail with an error (but see also the last paragraph of my comment).

I am proposing to modify the implementation in juggler's `lib/dao.js` along the following lines:

```js
// mock-up
DAO.updateOrCreate = function(data, options, cb) {
  if (dataHasIdField) {
    return this.create(data, options, cb);
  }

  if (modelHasForceId) {
    return this.replaceById(data.id, data, options, cb);
  }

  // continue with the current implementation
}
```

Here is one major downside I am aware of: if the user is trying to update an existing record that was deleted meanwhile, then the request will fail with 404 Not Found, which may be confusing. Or maybe not, since the intention was to update an existing records.

Thoughts?

**Comment by Amir-61** [comment]
@bajtos 
>I am proposing to modify the implementation in juggler's lib/dao.js along the following lines:

>// mock-up
DAO.updateOrCreate = function(data, options, cb) {
  if (dataHasIdField) {
    return this.create(data, options, cb);
  }
  if (modelHasForceId) {
    return this.replaceById(data.id, data, options, cb);
  }
  // continue with the current implementation
}

ummm... I got your idea...However, I guess you meant something like:
```
>// mock-up
DAO.updateOrCreate = function(data, options, cb) {
  if (!dataHasIdField) { // if (id === undefined || id === null)
    return this.create(data, options, cb);
  }
  if (modelHasForceId) {
    return this.replaceById(data.id, data, options, cb);
  }
  // continue with the current implementation
}
```


Are you also proposing we should get rid of implementation of `connector.replaceOrcreate`? I guess not...However Also please note having `forceId` set to True by default also breaks `updateOrCreate` as well...Also I think the quoted code ^ is your proposal for `replaceOrCreate` not `updateOrCreate`. Are you proposing we should use the following code for `updateOrCreate` instead:

```
// mock-up
DAO.updateOrCreate = function(data, options, cb) {
  if (!dataHasIdField) { // if (id === undefined || id === null)
    return this.create(data, options, cb);
  }
  if (modelHasForceId) {
    // `data` object contains id here
    return this.updateAttributes(data, options, cb);
  }
  // continue with the current implementation
}
```

**Comment by jannyHou** [comment]
> Now with forceId set, we are expecting clients to never provide an id field for new instances. In other words, if the instance data contains an id, then the assumption is that this is an existing instance.

Agreed 👍 

My understanding is since the current implementation is designed with the condition "forceId:  false", maybe we can check `modelHasForceId` first and decide returning `create()` or `replaceById()` if it's `true`,  then go on with current code:
```js
// mock-up
DAO.replaceOrCreate = function(data, options, cb) {
  if (modelHasForceId) {
    if (dataHasIdField) {
      return this.replaceById(data.id, data, options, cb);
    } else {
      return this.create(data, options, cb);
    }
  }
  // continue with the current implementation
}
```
BTW, I guess @bajtos means `replaceOrCreate` in his code, `updateOrCreate` is a typo? :P

**Comment by bajtos** [comment]
Sorry for the confusion.

1) Yes, you are right @Amir-61, my code snippet contained a bug, your version is correct.

2) Yes, I think we should fix `updateOrCreate` similarly.

3) No, I am not proposing to remove `connector.replaceOrCreate` (and the other connector method of `updateOrCreate`). We need these two connector APIs to correctly support the case where the clients are allowed to provide custom `id` values when creating new instances (`forceId:false`).

**Comment by Amir-61** [comment]
Since the issue is due to changes of forceId by your [PR](https://github.com/strongloop/loopback-datasource-juggler/pull/982) and apex own juggler and connectors I assign this issue to apex.

**Comment by Amir-61** [comment]
Assigning this issue and https://github.com/strongloop/loopback-datasource-juggler/issues/1185 to team-apex since the bug is related to changes of https://github.com/strongloop/loopback-datasource-juggler/pull/982 from Janny and Apex owns `loopback-datasource-juggler` and connectors. @0candy Please prioritize this in your team.
