### ISSUE TITLE
Persisted Model save method expected behaviour

### ISSUE THREAD

**Issue by aquid** [strongloop/loopback-datasource-juggler#1233]
Right now loopback says that it doesn't support partial update, but while going through the MongoDB connector docs I see that models save method supports partial updates or at least the tests do. By partial updates, I mean that I just pass particular fields of the model instance in save method and it overrides or creates those fields in existing JSON data and doesn't hamper other fields of the document.

As a proof of this, I am adding a link here of `loopback-connector-mongodb` tests file which does a testing for the partial update. 
[Test Case Link](https://github.com/strongloop/loopback-connector-mongodb/blob/master/test/mongodb.test.js#L1360)

Question: Is this the expected behavior of save method? Should it allow partial updates or is this a bug. I am trying to implement the same for [loopback-connector-elasticsearch](https://github.com/strongloop-community/loopback-connector-elastic-search) and need to understand actual implementation and working of this method.

cc @pulkitsinghal @bajtos @raymondfeng

**Comment by bajtos** [comment]
Hi @aquid, thank you for posting this query. I am afraid this is one of the gray undocumented areas where we have to follow the code to find out the answer.

AFAICT:
 - SQL-based connectors perform a partial update on `save()`, see [loopback-connector:lib/sql.js](https://github.com/strongloop/loopback-connector/blob/e384aa53ee639c35e01f9f9f9faf03ca2427271e/lib/sql.js#L473)
 - MongoDB connector calls MongoDB's method [save()](https://docs.mongodb.com/manual/reference/method/db.collection.save/) which performs a full replace.

> while going through the MongoDB connector docs I see that models save method supports partial updates or at least the tests do.
> Test Case Link

I am afraid that test case is broken. To unset an attribute, `delete post.title` is not enough ([here](https://github.com/strongloop/loopback-connector-mongodb/blob/4b39387fde2b4265c3d30bcb4618d87d19743885/test/mongodb.test.js#L1362)), one has to call `post.unsetAttribute('title')`. When I fix the test, it fails because the `title` property does get removed by the `save()` operation.

@Amir-61 @jannyHou I vaguely remember that we may have discussed this topic and the idea of changing `DAO.prototype.save` to call `replaceOrCreate` under the hood, but I cannot find any relevant issue. Do you happen to remember any more details?

Personally, I think `save()` should perform a full replace, that's what I would expect from a method with that name. To perform a partial update, one should be explicit and call `updateAttributes.

**Comment by jannyHou** [comment]
@bajtos Sorry I could not think of a partial/full update discussion regarding `save` :( 
There is a similar discussion of `updateAll` about "will it do a partial/full udpate of an array property": http://stackoverflow.com/questions/40111147/updateall-loopback-datasource-does-not-delete-deletions-inside-updated-data/40117755#40117755
But not seems like the same topic raised in this issue.

**Comment by Amir-61** [comment]
>@Amir-61 @jannyHou I vaguely remember that we may have discussed this topic and the idea of changing DAO.prototype.save to call replaceOrCreate under the hood, but I cannot find any relevant issue. Do you happen to remember any more details?

@bajtos Please see: https://github.com/strongloop/loopback-datasource-juggler/issues/916 and https://github.com/strongloop/loopback/issues/2393
