### ISSUE TITLE
Property formatters, constraints

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#128]
Where does the actual implementation of property formatters (trim, uppercase, ...) come from? Is it provided by a connector (or a database engine itself)? I could not find any references in-code, and it'd be interesting to be able to provide your own formatters (like urlify/slugify for example).

**Comment by Klowner** [comment]
:+1:

**Comment by nathanmarks** [comment]
@raymondfeng Seems like this has been open a while -- shouldn't this be removed from the documentation in loopback? It caused me a lot of grief yesterday

**Comment by BerkeleyTrue** [comment]
@raymondfeng This should definitely be remove from docs.

**Comment by crandmck** [comment]
I "commented out" that section from http://docs.strongloop.com/display/LB/Model+definition+JSON+file, so it won't be visible to general viewers. Sorry it caused problems.  Please mention or comment on https://github.com/strongloop/loopback/issues/523 when this issue is fixed so I add the docs back once it actually works.

**Comment by leventgunay** [comment]
hello from the other side!! this feature would be really helpful, i guess. looking forward to your updates. thanks.
