### ISSUE TITLE
Issues with `validatesUniquenessOf`

### ISSUE THREAD

**Issue by emilio-martinez** [strongloop/loopback-datasource-juggler#1321]
# Description/Steps to reproduce
**Bug**
Combining `findOrCreate` with `validatesUniquenessOf` results in failure after the first time.
https://github.com/emilio-martinez/loopbackValidatesUniquenessOfIssue

# Expected result
The expectation is that because the attempted operation involves finding OR creating, no validation should be required when there is a value to be found. However, even if there is, it seems that `validatesUniquenessOf` attempts validation despite the availability of an item that meets the filter parameters.

This is additionally more problematic with a `required` property because, for example, if we try to remove the property to work around the uniqueness issue—for example, on a `before save` operation hook—then we're faced with another validation error: `presence`.

It's a "catch 22". The same issues can be found on other operations such as `upsertWithWhere`.

In the repro code that I provided as "Steps to reproduce", simply run the server twice so that the boot script I created runs two times. you'll notice that the second time you'll get an error `ValidationError: The 'sample' instance is not valid. Details: 'uniqueAndRequired' is not unique (value: "Action")`

# Additional information
`darwin x64 6.9.2`
```
├── loopback@3.6.0
├── loopback-boot@2.24.0
├── loopback-component-explorer@4.2.0
```

**Comment by ssh24** [comment]
The main issue here persists in the base `findOrCreate` function in `dao.js`.
https://github.com/strongloop/loopback-datasource-juggler/blob/6c6df15286400e0dfbc2a458e0a074acc1abeecd/lib/dao.js#L1054-L1251

It has nothing to do with the `validatesUniquenessOf` rule and instead all types of validation rule would cause this issue. I suggest whoever taking on this task to write exhaustive test cases on each of the [validation rules](https://apidocs.strongloop.com/loopback-datasource-juggler/#validatable).

Before showing an example, I would like to make it clear the definition of `findOrCreate` function. It literally means what it is called, **if an instance exists with the given query, return that instance, and if it does not, create an instance with the given data**.

For example:

If I have the following model instances

```json
inst1: {
  "id": 1,
  "name": "foo",
  "age": 12
}
```

```json
inst2: {
  "id": 2,
  "name": "bar",
  "age": 15
}
```

```json
inst3: {
  "id": 3,
  "name": "baz",
  "age": 20
}
```

And I set a validation rule `Model.validatesUniquenessOf('id');`

After if I perform a `findOrCreate` call eg. 
```js
findOrCreate({"where": {"id": 1}}, {"id": 1, "name": "foo-new"}, cb);
```

This would throw the validation error even before trying to find the instance. Look at this [line](https://github.com/strongloop/loopback-datasource-juggler/blob/6c6df15286400e0dfbc2a458e0a074acc1abeecd/lib/dao.js#L1223). IMO, the function needs to be refactored so that it:
```
1. tries to find the instance with the query
2. if an instance is found return that instance
3. if it does not exist, validate the instance to be created
4. if validation succeeds, create the instance
5. if the validation fails, throw the validation error
```

**Comment by emilio-martinez** [comment]
I believe this is still active, not stale. @kjdelisle it looks like you were the last one following the progress here. Last update I see is "committed", but the issue still remains open. Any update?

**Comment by emilio-martinez** [comment]
@kjdelisle any word on this?

**Comment by kjdelisle** [comment]
@emilio-martinez Sorry, "committed" means that we were committing to it in a sprint, but we couldn't get to it due to the work on loopback@4.

If you know the fix, a pull request would definitely be welcome, as I can't promise when I (or someone else) will get to this.

**Comment by kjdelisle** [comment]
I'm surprised that this was still marked stale, but it must be that the bug label isn't in the ignore list, which needs fixing for sure.

**Comment by emilio-martinez** [comment]
@kjdelisle happy to take a look. At this point, would the intent be to target loopback@3 or loopback@4?

**Comment by bajtos** [comment]
> @kjdelisle happy to take a look. At this point, would the intent be to target loopback@3 or loopback@4?

FYI: Kevin is no longer actively maintaining LoopBack. 

loopback@4 is using the same ORM/data-access layer as loopback@3, which is this module (loopback-datasource-juggler). The patch fixing the problem should target juggler's `master` branch, that way the fix will be available to both LB3 and LB4 users.

**Comment by jamesjjk** [comment]
@bajtos Is there any update on this this issue still persists with enableOptimisedfindOrCreate. ValidateUniquenessOf, actually is validated after the event.

**Comment by bajtos** [comment]
We don't have bandwidth to look into this issue. LoopBack 3 is in Maintenance LTS mode now, we are providing only critical bug fixes & security fixes.  However, if you open a pull request to fix this issue in juggler's `master` branch (version 4.x used by LB4), then we will review the patch and if it the changes are not too risky to introduce regressions, then we can back-port the patch to `3.x` to make the fix available to LB3 users too.
