### ISSUE TITLE
Decide which connectors need loopback-2.x branch

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-datasource-juggler#1347]
juggler@2.x branch has lots of connector dependency failures, part of them are from loopback-connector-name@loopback-2.x

Copied from slack chat with @bajtos 
> the idea of `loopback-2.x` branches is to run the `master` code in the connector against `loopback-2.x` codebase, to verify that the latest version of the connector supports both LoopBack 2.x and LoopBack 3.x applications.
Therefore `loopback-2.x` branch needs to be periodically updated with the code from `master`.
If we no longer wish to maintain compatibility with both LoopBack 2.x and 3.x versions, then that's fine, but such change should be released as semver-major and ideally there should be a runtime check to tell people if they are using wrong combination of loopback vs. connector version.

If we decide to support connector@master compatible with loopback@2.x, take mysql as example: loopback-2.x branch is still using loopback-connector@^2.x as dependency, which according to the original purpose is not correct, and IMO it should use loopback-connector's loopback-2.x branch:
```js
// individual-connector@loopback-2.x 
// Sync with individual-connector@master branch
// except package.json:
  dependency: {
    loopback-connector: "git://github.com/strongloop/loopback-connector.git#loopback-2.x"
  },
  devDependency: {
    loopback-datasource-juggler: "^2.54.0"
  }
```
```js
// loopback-connector@loopback-2.x 
// Sync with loopback-connector@master
// except package.json:
  devDependency: {
    "loopback-datasource-juggler": "^2.54.0",
  }
```

**Comment by jannyHou** [comment]
Personal opinion: except cassandra, I am not aware of any reason why a connector's master branch could not be compatible with loopback 2.x. 
Appreciate more opinions shared on this. Thanks.

**Comment by jannyHou** [comment]
cc @strongloop/sq-lb-apex @rmg @bajtos @raymondfeng

**Comment by bajtos** [comment]
> If we decide to support connector@master compatible with loopback@2.x, take mysql as example: loopback-2.x branch is still using loopback-connector@^2.x as dependency, which according to the original purpose is not correct, and IMO it should use loopback-connector's loopback-2.x branch:

My understanding is different. The `loopback-2.x` branch should have the very same set of `dependencies` as the `master` branch. The only difference should be in the version of `loopback-datasource-juggler` listed in `devDependencies`.

The goal is to take the latest `master` version of `loopback-connector-mysql`, as it would be installed by a LoopBack application, and verify what happens when the LoopBack application in question is using LoopBack 2.x.

Scenario A) - covered by `npm test` on `master`:
 - `lb app` + select 3.x version
 - `lb dataSource` + use our connector
 - run some tests

Scenario B) - covered by `npm test` on `loopback-2.x`
 - `lb app` + select 2.x version
 - `lb dataSource` + use our connector
 - run some tests

Note that `loopback-connector` was intentionally decoupled from juggler, it is (should be?) written in such way that it's ok for each specific connector (MySQL, MongoDB, etc.) to depend on whatever version they like, and it's ok to have multiple copies of `loopback-connector` module in application's dependency tree.

Let's take loopback-connector-mysql for an example of what needs to be done with `loopback-2.x` branch. The `master` branch lists the following dependencies/devDependencies:

```json
{
  "dependencies": {
    "async": "^0.9.0",
    "debug": "^2.1.1",
    "loopback-connector": "^4.0.0",
    "mysql": "^2.11.1",
    "strong-globalize": "^2.5.8"
  },
  "devDependencies": {
    "bluebird": "~2.9.10",
    "eslint": "^2.13.1",
    "eslint-config-loopback": "^4.0.0",
    "loopback-datasource-juggler": "^3.0.0",
    "mocha": "^2.1.0",
    "rc": "^1.0.0",
    "should": "^8.0.2",
    "sinon": "^1.15.4"
  }
}
```

In the `loopback-2.x` branch, I would expect the following:

```json
{
  "dependencies": {
    "async": "^0.9.0",
    "debug": "^2.1.1",
    "loopback-connector": "^4.0.0",
    "mysql": "^2.11.1",
    "strong-globalize": "^2.5.8"
  },
  "devDependencies": {
    "bluebird": "~2.9.10",
    "eslint": "^2.13.1",
    "eslint-config-loopback": "^4.0.0",
    "loopback-datasource-juggler": "^2.0.0",
    "mocha": "^2.1.0",
    "rc": "^1.0.0",
    "should": "^8.0.2",
    "sinon": "^1.15.4"
  },
```

Here is the diff:

```diff
     "eslint-config-loopback": "^4.0.0",
-     "loopback-datasource-juggler": "^3.0.0",
+     "loopback-datasource-juggler": "^2.0.0",
     "mocha": "^2.1.0",
```

**Comment by dhmlau** [comment]
@jannyHou  @bajtos , currently CI on juggler 2.x branch is failing because the downstream are failing.  The following are the connectors in `loopback-2.x` branch with failed CI: 
- cloudant
-  dashdb
-  db2
-  db2z
-  mqlight
-  mysql
-  oracle

I guess we still aim to fix it (including fixing the juggler version) too?

**Comment by jannyHou** [comment]
@dhmlau I agree..

**Comment by dhmlau** [comment]
@jannyHou , if we're still aiming to keep `loopback-2.x`, is this issue good to close?

**Comment by jannyHou** [comment]
@dhmlau sure, I am closing it.
