### ISSUE TITLE
Don't rely on [function].name (Internet Explorer problem)

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-datasource-juggler#375]
`[function].name` is not available in IE10, or any other IE version. It returns undefined.

However, function name is becoming a standard part of the language in ES6, therefore I don't think we should be handling this issue in loopback. For example, loopback requires at least ES5, so we are manually loading es5-shim for the unit tests running in PhantomJS.

Tasks:
- [ ] Update LoopBack documentation and explicitly mention that LoopBack requires ES5 and function.name, provide instructions on how to setup such environment in older browsers (most notably IE). Since IE has conditional include directives, it should be fairly easy to exclude the shim in other browsers.
- [ ] Implement caching mechanism for [Function.name](https://github.com/JamesMGreene/Function.name).

See #348 for background.

**Comment by loay** [comment]
On January 12, 2016 Microsoft announced end of support for IE10, IE9, and IE8 on Windows 7, Windows 8.1, and Windows 10. Internet Explorer 11 is now the last version of Internet Explorer on these platforms which will continue to receive security updates, compatibility fixes, and technical support.

We will monitor the issues in case we observe the same behavior with either IE 11 or MS Edge with Loopback 3 or 4. Closing this issue for now since it is not relevant and won't be fixed.
