### ISSUE TITLE
Name for relations

### ISSUE THREAD

**Issue by jesusbv** [strongloop/loopback-datasource-juggler#380]
In my case, decided to change the relation name in user.json

"profileImage": {
      "type": "belongsTo",
      "model": "File",
      "foreignKey": "profileImage"
    }

which gives me the user-file relation

IT IS NOT WORKING.

fixed with
"file": {
      "type": "belongsTo",
      "model": "File",
      "foreignKey": "profileImage"
    }

weird. Weird but it is working.
So, can we not change the name of the relation even when we specify the table and everything?

**Comment by fabien** [comment]
This is to be expected - while it is not as noticeable from the REST API, it becomes clear in plain code: the relation accessor/proxy is a property of the model, just as the foreignKey would be. So if the names are equal, one will clobber the other.

**Comment by dossorio** [comment]
Thanks @fabien for replying !

In my case, as I am new to loopback It took me quite a while to notice it... :)

Anyway, using this working model definition:
```javascript
{
  "name": "user",
  "relations": {  
    "profileImage": {
      "type": "belongsTo",
      "model": "File",
      "foreignKey": "profileImageId"
    } 
  }
}
```
What caused a little bit of confusion (Apart of what stated above) was the fact that, we have an profileImageId property inside the object and we have another different thing, which is the relation, from where we can get the related object.

For example, if we want to consume /users/1 and get the File related object inside the response, if I am right, we would have to hook in findById, something like:
 ```javascript
      User.findOne(
      {
        where: {id: user.id},
        include: ['profileImage']
      },
      function(err, notification) {
        if (err) return next(err);

        delete user.__data.profileImageId;

        ctx.result = notification;

        next();
      });
```

Note the following:
- We have to add the relation name inside the include statement
- We have to remove profileImageId to avoid sending it inside the response

For me, it would be clearer if we would access profileImage property and we get the object directly instead of having two different things... And sometimes accessing it by the relationName and other by the foreignKey.

What do you think ?

Thanks !

**Comment by raymondfeng** [comment]
You can use http://docs.strongloop.com/display/LB/Remote+hooks.
