### ISSUE TITLE
Add fine-grained migration APIs

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-datasource-juggler#466]
LB supports `automigrate` and `autoupdate` today. It will be useful to expose more fine-grained apis so that application developers can have better control of the process.

**Comment by alFReD-NSH** [comment]
I'm also using postgres and I would love the following functionalities in autoupdate(Of course all optional): 

- Old columns are not deleted, and if they have `NOT NULL`(required property/column), `NOT NULL` should be dropped(so that new data will work fine without it).
- If column has a type change, then the old column should be renamed so the old data is not removed, mentioned in here: strongloop/loopback#1942
- If column has a type change, the old data is casted to the new type whenever possible.
- A dry-run mode where the connector will only return a string which is the sql changes to be made without executing them, mentioned in here: strongloop/loopback#207
- If a new column is required and has a default value, then all the rows should have that default values(right now it fails), mentioned in here: strongloop/loopback-connector-postgresql#123.

**Comment by laurentdesmet** [comment]
+1 for this feature because now autoupdate can lead to dataloss because columns can be removed as mentioned above (issue strongloop/loopback#1942). Maybe the documentation should be updated because now this [page](https://docs.strongloop.com/display/public/LB/Creating+a+database+schema+from+models) states 
> When tables with data exist, use auto-update to avoid data loss.

which is a dangerous statement to make because autoupdate can actually remove data.

**Comment by e-part** [comment]
+1 - It would be great if I can see a SQL which shows only the changes made to the DB
before deciding whether it's safe to run it.
