### ISSUE TITLE
upsert does not set ctx.instance

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-datasource-juggler#487]
using a "PUT" (Update an existing model instance or insert a new one into the data source) where there isn't an existing record, ctx.data is set, not ctx.instance, even if it is a new record

this makes it impossible to perform certain tasks on the creation of a new record using PUT

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by fabien** [comment]
@jmls which "PUT" are you referring to? I assume you mean `PUT /modelName` which maps to `updateOrCreate`.

If your datasource supports `updateOrCreate` directly, it will be used. In this case there will not be a `ctx.instance`.

However, if your dataSource does not cater for this optimized scenario, it will perform a find and then performs `updateAttributes` on the instance. In turn, you will have a `ctx.instance` in this case.

**Comment by bajtos** [comment]
@jmls the current implementation of `updateOrCreate` performs a partial update when the record was found, that's why there is `ctx.data` instead of `ctx.instance`.

> However, if your dataSource does not cater for this optimized scenario, it will perform a find and then performs `updateAttributes` on the instance. In turn, you will have a ctx.instance in this case.

Let me correct this, you will have `ctx.data` containing the list of property values to change, and `ctx.currentInstance` pointing to the model instance being updated.

See the discussion in #482 for more information.
