### ISSUE TITLE
Default foreignKey field type on polymorphic belongsTo should be modelTo idType, not modelFrom idType

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-datasource-juggler#507]
Hello!

Ran into a problem today under the following conditions,

1. MongoDB as a dataStore
2. Polymorphic relation between **ModelA** and **ModelB**,
  1. **ModelA** hasMany polymorphic **ModelB**
  2. **ModelB** belongsTo polymorphic **ModelA**
3. **ModelB** has a id key that differs in type from that of **ModelA**. For example, ``string``.

On call to ``ModelA.hasMany(...)``, the **ModelB** foreignKey field is auto-vivified with type ``ObjectID``.
On subsequent call to ``ModelB.belongsTo(...)``, the foreignKey field is redefined as the ``ModelB.id`` field type (such as  ``string``). 

**Expected behavior: the foreignKey field type for a polymorphic belongsTo should default to the modelTo idType.**

See the following project to reproduce: https://github.com/doublemarked/loopback-polymorphic-belongsTo-default-types

The relative code is at [relation-definition.js#L1131-L1132](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L1131-L1132)

**Comment by fabien** [comment]
Because `modelTo` is unknown upfront (it's polymorphic), we cannot rely on `modelTo` for getting the `foreignKey` type. Note that `modelTo` is `null` in the code that you mention - which is to be expected.

In this case, you should set the type explicitly if using the `polymorphic.idType` option; the best guess fallback tries to use the same type as `modelFrom`, taking into consideration that the id type is similar (and probably on the same data source - ObjectID for MongoDB, Number for a relational DB).

**Comment by doublemarked** [comment]
Thank you Fabien, your explanation makes total sense. It should
have occurred to me when writing the ticket that modelTo would be unknown.

It is unfortunate that this idType property is completely undocumented. But
after I discovered it in the code I used it to fix the problem for our
project.

**Comment by fabien** [comment]
@crandmck can you add this to the docs? Thanks!

**Comment by crandmck** [comment]
Added #517.  Could you please link to an example of using `polymorphic.idType` option?  That will make it much easier to doc.
