### ISSUE TITLE
Operation hooks: skip?

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#519]
I think it would be useful to be able to skip subsequent hooks, without throwing an error (which seems the only way to halt the queue). Proposal:

```
Model.observe('before save', function(ctx, next) {
  next(null, ctx.instance && ctx.instance.disabled); // skip if second callback arg == true
});
```

**Comment by fabien** [comment]
As an update, I would like to propose: whenever 2 arguments are returned, the 2nd argument is used, and the rest of the operations are skipped. This would signal that the hook handled the operation, for example, and there's no need to proceed.

```
Model.observe('before save', function(ctx, next) {
  doStuffHere(function(err, result) {
     next(err, result); 
  });
});
```

/cc @bajtos @raymondfeng

**Comment by bajtos** [comment]
I don't like this very much. At the moment, users don't have a good way how to define order of hook handlers, therefore it will be difficult to tell which hooks are skipped and which are not.

Also because the hook handler does not know which specific method is being invoked, how is the hook supposed to know what is the expected result of the operation?

What feature are you trying to implement?

Depending on your answer, we may find that [per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397) are more suitable for the job.

**Comment by fabien** [comment]
@bajtos agreed, it might not always be possible to know the order of registered hooks. I was primarily interested in a way to take charge of the `save` step in a hook, so the default DAO logic would be overruled. I'm not sure this makes sense, but I had use-cases for this already.

However, it turns out that this particular scenario could be resolved by a hook that would do whatever it needed to do, and set `ctx.data` to a blank `object`, which rendered the subsequent `save` as a 'noop'.

Which is why I created this PR: https://github.com/strongloop/loopback-connector-mongodb/pull/117

**Comment by fabien** [comment]
@bajtos I'm closing this, but please see the comment above.
