### ISSUE TITLE
Uniqueness validation check will always fail User.findOrCreate() if connector supports optimized findOrCreate

### ISSUE THREAD

**Issue by clarkorz** [strongloop/loopback-datasource-juggler#529]
The User Model has two uniqueness fields: username and email. Currently, if the connector supports optimized findOrCreate, `DAO.findOrCreate()` will notify `access` and `before save` hooks and validate the data before calling connector's `findOrCreate`.

The problem is, if the the user already exists in the database, `DAO.findOrCreate()` doesn't know that yet, so it will validate the data, and it will fail the whole `findOrCreate` due to the uniqueness of  username and email.

@bajtos throughs?

**Comment by bajtos** [comment]
Hmm, that's a sort of catch-22, isn't it?

Here is a possible solution: when the validation fails because of uniqueness violations, then perform a regular unoptimized find/findOne. If the record exists, then return the record. If it does not exist, then report back the original validation error.

Thoughts?

**Comment by clarkorz** [comment]
The original reason that I want connector optimized `findOrCreate` is it can make sure that there is only one record that match a certain query. If we fall back to a normal `findOne/create`, it won't make sense.

How about this: when the validation fails because of uniqueness violations only, then we check that if all uniqueness fields are in `query.where` with equal operator only. If they do, then we omit the validation error and proceed.

**Comment by bajtos** [comment]
> The original reason that I want connector optimized findOrCreate is it can make sure that there is only one record that match a certain query. If we fall back to a normal findOne/create, it won't make sense.

I am not suggesting to fall back to normal findOne/create, but only to call `findOne` to check if the model exists.
 - If the model exists, then we return it and we are done. That's what would happen in both atomic and non-atomic implementations.
 - If the model does not exist, then we return the validation error, because we cannot create an invalid model. This is the correct result for both atomic and non-atomic implementation.

Here is the (only?) situation when we would return an incorrect result:
 1. ClientA makes a "findOrCreate" request for an existing record.
 2. Uniqueness validation reports an error.
 3. ClientB deletes the existing record.
 4. "findOrCreate" checks the database to see if the record exists.
 5. No record was found and a validation error is reported back to the client.

> How about this: when the validation fails because of uniqueness violations only, then we check that if all uniqueness fields are in query.where with equal operator only. If they do, then we omit the validation error and proceed, else report the error.

This feels very brittle and can possibly cause invalid data to be written to the database.

--- 

I think we are discussing a wrong think. If you look at the way how uniqueness validation is implemented, it checks if the record found has the same id as the record being modified.

[lib/validations.js#L349-L354](https://github.com/strongloop/loopback-datasource-juggler/blob/b5188a5af410c0a6794068ae03a8ef560051b318/lib/validations.js#L349-L354)

```js
    if (found.length > 1) {
      err();
    } else if (found.length === 1 && (!this.id || !found[0].id || found[0].id.toString() != this.id.toString())) {
      err();
    }
    done();
```

Can you please debug/investigate why the id check is not working correctly for you? Perhaps it's the same problem as in #522?

/cc @raymondfeng

**Comment by bajtos** [comment]
I can smell two problems in the code pasted above:
 1. It assumes that the id column is called `id`, which is not necessarily true.
 2. It uses `id.toString()` which probably may not play well with `ObjectID` values.

**Comment by mediapolis** [comment]
This issue is causing issues with passport functionality:

https://github.com/strongloop/loopback-component-passport/issues/123

Uniqueness validations before the find phase of findOrCreate probably need some special handling as this does not behave as expected.

**Comment by Narrator** [comment]
+1

**Comment by ataft** [comment]
+1

It makes no sense to validate for uniqueness or any other "create" operation if the object already exists (i.e. is "found").
