### ISSUE TITLE
Don't inherit operation hooks when extending models

### ISSUE THREAD

**Issue by jcsmesquita** [strongloop/loopback-datasource-juggler#580]
Hey @bajtos ! 

I'm using the latest loopback-datasource-juggler@2.26.4 and ran into a hiccup

Scenario: Model "foo" extends model "bar" via a "base" property defined in foo.json

Then I hit DELETE api/foo/123 ...
I expect this to trigger: Foo.observe('before delete', ...
But instead this triggers: Bar.observe('before delete', ...

Is this a bug?

**Comment by jcsmesquita** [comment]
Actually I just realised both hooks get triggered, it's just that the base hook is triggered first...

**Comment by jcsmesquita** [comment]
I'm also having to clear the _observers object for every model each time the app does a rerun (i.e. when using mocha watch) otherwise I get multiple functions piling up in my observed events...

**Comment by bajtos** [comment]
Hi @jcsmesquita, 

>  both hooks get triggered, it's just that the base hook is triggered first...

This is intended. It allows you to setup the hook in the base model only and have it called in all submodels.

Can you please describe your use case (scenario) in more details, so that we can find a way that will solve the problem for you, either by using the existing API or by creating a new one?

**Comment by PowerP** [comment]
Hi,

I have the same Problem. I do same cascading deletes in main modeI don't want to have in the extended model. 
Do you have a tip for me, how to overcome this problem?

thx
