### ISSUE TITLE
update/updateAll does not respect option: notify: false

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-datasource-juggler#596]
This is an inconsistency and prevents cases that would otherwise result in an infinite loop.

**Comment by Amir-61** [comment]
Yea. I agree with you!  unfortunately we don't have support for notify for a few method including `update/updateAll`. It can be considered as a bug, but since we never had any support for `notify` for `update/updateAll` I label it as feature, although I agree it can be a bug because of inconsistency.

Thanks for the ticket :-)

**Comment by rahpuser** [comment]
Are you open for a PR, it doesn't seem to be difficult to add this flag for update/updateAll and I think is something really needed.
