### ISSUE TITLE
Polymorphic hasMany relations

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback-datasource-juggler#765]
Although it is possible for a Model to have a polymorphic belongsTo relation (i.e. a Comment belongsTo a MediaItem - Video or Picture), it doesn't seem to be possible for a Model to have polymorphic hasMany relations (i.e. a Vet hasMany Patients - Dog or Cat).

Although the documentation mentions polymorphic hasMany, it does not seem to be referring to the functionality I am.

If I am mistaken, please let me know! Otherwise, consider this a feature request!

**Comment by 0candy** [comment]
Correct me if I'm wrong, but you're trying to set up a relation between a Vet and Patients? That should work.
```{
  "name": "Vet",
  "base": "PersistedModel",
  ...
  "relations": {
    "link": {
      "type": "hasMany",
      "model": "Patients",
      "polymorphic": {
         "foreignKey": "patientId"
      }
    }
  }
...
}
```
https://docs.strongloop.com/display/APIC/Polymorphic+relations#Polymorphicrelations-HasManypolymorphicrelations

**Comment by jannyHou** [comment]
@gausie @0candy I think the doc is a little confusing:

> it is possible for a Model to have a polymorphic belongsTo relation (i.e. a Comment belongsTo a MediaItem - Video or Picture)

Actually even though we has headline like 
```
HasMany polymorphic relations
HasManyThrough polymorphic relations
BelongsTo polymorphic relations
```
, they are describing a same relation as "Comment belongsTo a Medialtem - Video or Picture". 
I could not find a reverse example like "a Vet hasMany Patients - Dog or Cat".

The documentation is depicting the same relation from different perspective, like when you define a polymorphic relation, in some model's json you need to define a hasMany relation while other model need a belongsTo relation, that's what those headlines imply.

Anyway, the polymorphic relation documentation needs improvement and I will also improve the loopback-example-relations to give users a better understanding of how it works. Thanks everyone!

**Comment by TrevorPage** [comment]
I've stumbled across this tracker because I *think* it is referring to the same problem I've just been battling with.

I have been trying to implement a polymorphic relationship of this form:

Human hasOne Pet, where Pet can be Dog or Cat.

But, rather like @jannyHou pointed out, it seems that the polymorphism cannot work in that direction. It seems that the only way I'm allowed to do this is:

Human belongsTo Pet.

Trying to attempt a 'hasOne' polymorphic relation (Human hasOne Dog|Cat) results in an exception due to this validation in loopback-datasource-juggler datasource.js:

```
  // polymorphic relations other than belongsTo should have `model` defined
  if (r.polymorphic && r.type !== 'belongsTo' && !r.model) {
    msg = g.f('{{polymorphic}} %s relation: %s requires param `model`', r.type, rn);
    code = 'POLYMORPHIC_NOT_BELONGS_TO_MISSING_MODEL';
  }
```

Is there a fundamental reason for this that I'm missing?

**Comment by aharbis** [comment]
Thanks for re-opening this @jannyHou, look forward to your feedback.

**Comment by jannyHou** [comment]
@aharbis 

Take `Picture` belongsTo either a `Reader` or `Author` as an example, the concept "polymorphic" is implemented by adding a property called `discriminator` on model `Picture`, which specifies the name of the model that it belongs to. Therefore `Picture` uses two properties: `discriminator` and `foreignKey` to know who is its parent.

And this also implies scenario `Human` hasOne either `Dog` or `Cat` won't work, since property `discriminator` is added on the Model with foreign key(child model), not parent model `Human`.

Such a scenario should use polymorphic `ReferenceOne` but we don't support polymorphic reference relations yet...

**Comment by cmsloan** [comment]
Regarding the current design, its clear that as implemented `Human` hasOne `Dog` or `Cat` won't work for the reasons mentioned. I think the question is, is there some reason this has to be implemented this way? 

It seems reasonable (and needed in cases like ours and the ones mentioned above) to be able to provide the `discriminator` on the parent. 

The `Human` model would have a `hasOne` relationship named `pet`. The `petID` would point at the ID of the pet, and the `petType` would specify if it is a `Dog` or `Cat` (similar to how belongsTo currently works).
