### ISSUE TITLE
Passing arrays of ids to `Model.relation.add()`

### ISSUE THREAD

**Issue by gaurav21r** [strongloop/loopback-datasource-juggler#846]
I have the following Code

``` js
async function createData() {       
    await (await Teacher.create({name: 'Suja', id: 1})).classes.add(1)
    await (await Teacher.create({name: 'CVR',  id: 2})).classes.add([1, 3])
}
```

Please excuse the **ES7 async / await** usage in the example, just makes the code cleaner to understand!

Basically `Teacher` `Suja` is created and is related to `classes` of `id = 1`.
`Teacher` `CVR` is created but is not related to `classes` of `id = 1` and `id = 2`.

I am coming from the Waterline world, and I really find the ability to assign multiple relations with a single statement an increasingly used feature. Basically [this](https://github.com/balderdashy/waterline-docs/blob/master/models/associations/many-to-many.md#with-an-array-of-new-record) is what I mean!

Either I'm doing something wrong or this is a feature request! :)

**Comment by gaurav21r** [comment]
Forgot! These are my model definitions:

```js
var Class = loopback.createModel({
    name: 'class',
    properties: {
        name: 'string'
    }
})
var Teacher = loopback.createModel({
    name: 'teacher',
    properties: {
        name: 'string'
    },
    relations: {
        classes: {
            model: 'class',
            type: 'hasAndBelongsToMany'
        }
    }
})
```

**Comment by gaurav21r** [comment]
@raymondfeng @bajtos @wertlex @mazesoul @superkhau Your thoughts?

**Comment by bajtos** [comment]
@gaurav21r thank you for reporting this feature request, it looks reasonable to me in principle.

However, there is an important catch. Loopback connectors don't provide a batch-create API at the moment. I.e. `add([1,2])` would have to make two database calls under the hood. This complicates things a lot - consider the case when the first call succeeded but the second one failed. What should `add([1,2])` report in such case? Do you expect us to roll-back the first database request? What if roll-back fails?

In order to implement this feature properly, we would have to implement an atomic batch-create method in all connectors and loopback-datasource-juggler. It's doable, but it's quite a large piece of work.

**Comment by demiro** [comment]
why is this closed? this is an important feature!
