### ISSUE TITLE
Relations endpoints are not exposed on explorer.

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback-datasource-juggler#973]
Hi, 
I'm setting relations in code but the relations endpoints are not exposed on explorer. Docs preference : https://docs.strongloop.com/display/APIC/Creating+model+relations.

For example, I set `A.hasMany(B)` but the endpoint `/api/A/:id/B` is not appeared on explorer.

Is there any additional configurations  to get it exposed ?

Many thanks.

**Comment by Amir-61** [comment]
Hey @dongmai,

If you generate the relation via `slc loopback:relation` you do get the relation endpoints in your explorer... but if you do it programatically like `foo.hasMany(bar)` you don't get the relation endpoint in your explorer and the reason is that explorer is booted before your boot script which is designed this way on purpose I believe... @superkhau by any chance could you confirm that the order of booting explorer which happens before booting boot script was on purpose and cannot be the other way?

**Comment by jannyHou** [comment]
@Amir-61 @dongmai Yes if you want to see endpoint in explorer you have to define it in `common/models/modelName.json` instead of in boot script.

Please check code in loopback-boot about the booting sequence of a loopback app:
https://github.com/strongloop/loopback-boot/blob/master/lib/executor.js#L38

The relationdefinition builder is triggered during `setupModels`, it will wrap relation methods for remoting, like wrapping `modelA.modelBs.create` as an endpoint `modelA.__get__modelBs`, which will be recognized by strong-remoting.
And explorer is booted when `setupComponents`.
They all happen before boot-scripts are executed.

**Comment by Amir-61** [comment]
Thanks @jannyHou 
I believe this is good to be closed now. @dongmai  Please feel free to open it if you have any more questions in this area.
