### ISSUE TITLE
Loaded hook triggered multiple times for a single PUT REST api call.

### ISSUE THREAD

**Issue by peeter-tomberg** [strongloop/loopback-datasource-juggler#991]
I've created a simple mixin in the hopes to get the models original state and log all changes made to the model in the after save hook. The problem is, the "loaded" hook is triggered 3 times for a simple PUT request made to the REST API, with inconsistent payloads. 

Example code:

``` javascript
module.exports = (Model) => {
    'use strict';
    Model.observe('loaded', (context, next) => {
        console.log('loaded hook', JSON.stringify(context));
        next();
    });
    Model.observe('after save', (context, next) => {
        console.log('after save hook', JSON.stringify(context));
        next();
    });
};

```

Result:

"loaded" triggered 3 times with inconsistent contexts:
- first time the context.instance is defined (with the data that is loaded from the database).
- second time the context.instance is defined  (with the data that is loaded from the database).
- third time has context.data key defined (with the data I passed into the PUT request, not the data that is present in the database).

the third "loaded" and the "after save" share the same hookState, while the first 2 do not.

**Comment by Amir-61** [comment]
Could you please provide a sample repo using out [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) reproducing the issue.

Thanks!

**Comment by Amir-61** [comment]
There are already tests which confirm `loaded` hook gets triggered just once; please see https://github.com/strongloop/loopback-datasource-juggler/blob/c8ade9e9d00737e8c4be266168b579ca9d72573e/test/persistence-hooks.suite.js#L1812-L1823

Since there are tests which confirm the `loaded` hook gets triggered once and inactivity of this ticket, I'm closing this issue now.

Please feel free to open an issue with a sample repo reproducing the issue. Thanks!
